First day project
safar1212/reactjs-bookstore pull request #1
Opened 2022-07-07 14:49 UTC by safar1212

In this pull request:
I created a react app.
Created components.
Installed linters.

2022-07-07 15:04 UTC, ShahierNashaat requested changes
Hi @safar1212 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 15:04 UTC, ShahierNashaat commented on src/components/singleBook.js
> +);
- [ ] Kindly be noticed that the SingleBook component should have two props the title and the author and renders them.
- [ ] Also it should have a button for removing books the button wouldn't remove the books *yet*,

2022-07-07 15:04 UTC, ShahierNashaat commented on src/components/displayBooks.js
> +);
- [ ] Kindly be noticed that you should render a list of books using the `SingleBook` component.
- [ ] Also you should remove the remove button as it should be in the `SingleBook` component.

```
const DisplayBooks = () => 
const books = [];
(
  <div className="book-list">
   books.map((book) => {
       return <SingleBook title={book.title} author={book.author} />
    }
    <AddBook />
  </div>
);
```

2022-07-08 08:38 UTC, aimemalaika approved these changes
Hi @safar1212, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 08:40 UTC, merged